config/routes.rb
Rails.application.routes.draw do
  root to: 'students#index'
  resources :students
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord

validates :name, presence: true, length: { minimum: 3 }
validates :age, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action:set_student, only:[:show, :edit, :update, :destroy]
def index
    @students = Student.all
end
def show
end
def new
    @student = Student.new
end
def create
    @student = Student.new(student_params)
    @student.save
    flash.alert = "User Added Successfully"
    redirect_to :action => :index
end
def edit
end
def update
    @student.update(student_params)
    redirect_to :action => :index
end
def destroy
    @student.destroy
    redirect_to :action => :index
end
private
def student_params
    params.require(:student).permit(:name, :age, :image)
end

def set_student
    @student = Student.find(params[:id])
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
</nav>
    <%= yield %>

  </body>
</html>

app/views/shared/_display.html.erb
 <tr>

      <td><%= student.id%></td>
      <td><%= student.name%></td>
      <td><%= student.age%></td>
      <td>
       <div class = "btn-group">
      <%=button_to 'Details',student_path(student), method: 'get', class: "btn btn-info"%>
      <%= button_to 'Delete', student_path(student), method: 'delete', class: "btn btn-danger" %>
      <%= button_to 'Edit', edit_student_path(student), method: 'get', class: "btn btn-secondary"%>
      </div>
</td>

    </tr>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">DEMO</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only"></span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
    </ul>
  </div>
</nav>

app/views/students/edit.html.erb
<h1>Update A new Student</h1>

<%= form_for @student, local: true do |f| %>
  <div class = "form-group mt-4">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>

    <%= f.label :age %><br/>
    <%= f.text_field :age %>

  </div>
<br><%= f.submit "update", class: 'btn btn-primary mt-4' %>
  </div>
<% end %>
<%= link_to 'Back', {:action => 'index'} %>

app/views/students/index.html.erb
<%= render "shared/navbar" %>
<h1 class= "justify-content" style=" text-align:center; margin-top: 40PX;">WellCome to the Website</h1>
<h1><%- puts "Wakeel Mustfa is here"-%></h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Age</th>
       <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
<%= render partial: "shared/display", collection: @students , :as => :student %>
<%=button_to 'Add Student','students/new', method: 'get' ,class: "btn btn-success"%>
  </tbody>
</table>

app/views/students/new.html.erb
<h1>Create A new Student</h1>

<%= form_for @student, local: true do |f| %>
  <div class = "form-group mt-4">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>

    <%= f.label :age %><br/>
    <%= f.text_field :age %>
  </div>
<br><%= f.submit "Save", class: 'btn btn-primary mt-4' %>
  </div>
<% end %>
<%= link_to 'Back', {:action => 'index'} %>

app/views/students/show.html.erb
<h1>Student Details</h1>
<p><%= @student.id%></p>
<p><%= @student.name%></p>
<p><%= @student.age%></p>